### ISSUE TITLE
Question on the theory mean calculation

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/tomo_challenge#5]
So, I'm puzzled by this line: 

https://github.com/LSSTDESC/tomo_challenge/blob/c89d57eb195c5dcdd1e54294678549590e4af86a/tomo_challenge/metrics.py#L212

Shouldn't it be `C_obs` instead i.e. including the noise power spectrum in auto-spectra? or am I missing something? 

For the initial metric of S/N I wasn't too sure, but for the FoM, I would have definitely included the noise.

**Comment by joezuntz** [comment]
No,  this is correct, because we would compare to a noise-subtracted estimate of the observed signal in any parameter estimation.  It doesn't actually matter either way here, though, because for Fisher we don't use the mean. And for the SNR metric it would add a constant offset to all the results I think.

**Comment by EiffL** [comment]
Great thanks for the clarification :-) I hadn't thought the data vector would come in noise subtracted. that answers it.
